#!/usr/bin/env bash
# llm-wiki-kit renderer — turn one agent-neutral command source
# (commands-src/<name>.md) into a specific agent's command/prompt file.
#
#   render.sh <agent> <wiki_dir> <src_file>   > rendered output
#
# <agent>     one of: claude gemini codex opencode cursor antigravity
# <wiki_dir>  absolute path baked into the command, OR the literal "@dynamic"
#             to emit a runtime shell resolver (claude only; used for the
#             committed Claude plugin where the path isn't known at build time).
# <src_file>  path to a commands-src/*.md neutral source.
#
# Differences each agent needs (format, args token, shell support) live in the
# case statements below — add a new agent by extending them.
set -euo pipefail

AGENT="${1:?agent required}"
WIKI="${2:?wiki dir (or @dynamic) required}"
SRC="${3:?source file required}"

[ -f "$SRC" ] || { echo "render.sh: no such source: $SRC" >&2; exit 1; }

# --- frontmatter / body helpers ------------------------------------------
field() { # field <name> — print a frontmatter value (first match), dequoted
  awk -v f="$1" '
    BEGIN { c = 0 }
    /^---[ \t]*$/ { c++; next }
    c == 1 && $0 ~ "^"f":" {
      line = $0; sub(/^[^:]*:[ \t]*/, "", line)
      gsub(/^"|"$/, "", line)
      print line; exit
    }' "$SRC"
}
body() { # everything after the closing frontmatter delimiter
  awk 'BEGIN{c=0} /^---[ \t]*$/{c++; next} c>=2{print}' "$SRC"
}

# escape a string for safe use as a sed replacement (delimiter |)
sed_rep() { printf '%s' "$1" | sed -e 's/[&|\]/\\&/g'; }

DESC="$(field description)"
HINT="$(field argument-hint)"
CLAUDE_TOOLS="$(field claude-tools)"
NAME="$(field name)"; [ -n "$NAME" ] || NAME="$(basename "${SRC%.md}")"

# --- per-agent args token -------------------------------------------------
# Agents that expand arguments get their native placeholder; agents that only
# insert-and-edit the prompt (cursor, antigravity) get the human hint instead.
case "$AGENT" in
  claude|codex|opencode) ARGS_TOKEN='$ARGUMENTS' ;;
  gemini)                ARGS_TOKEN='{{args}}' ;;
  cursor|antigravity)    ARGS_TOKEN="${HINT:-<input>}" ;;
  *) echo "render.sh: unknown agent: $AGENT" >&2; exit 1 ;;
esac

# --- wiki-path substitution (baked vs dynamic) ----------------------------
DYNAMIC=0
if [ "$WIKI" = "@dynamic" ]; then
  DYNAMIC=1
  [ "$AGENT" = "claude" ] || { echo "render.sh: @dynamic only supports claude" >&2; exit 1; }
  WIKI_SUB="WIKI"   # body refers to the word WIKI; resolver prints the real path
else
  WIKI_SUB="$WIKI"
fi

# render the body with both tokens substituted
RENDERED_BODY="$(body \
  | sed "s|{{ARGS}}|$(sed_rep "$ARGS_TOKEN")|g" \
  | sed "s|{{WIKI}}|$(sed_rep "$WIKI_SUB")|g")"

# resolver preamble used only by the dynamic Claude plugin build
DYN_RESOLVER='Knowledge wiki directory (resolved): !`sh -c '"'"'c="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/knowledge-wiki.path"; if [ -n "$KNOWLEDGE_WIKI_DIR" ]; then echo "$KNOWLEDGE_WIKI_DIR"; elif [ -f "$c" ]; then cat "$c"; else echo "$HOME/personal/knowledge-wiki"; fi'"'"'`

Use the path shown above as **WIKI**.'

# --- emit, per agent format ----------------------------------------------
case "$AGENT" in
  claude)
    tools="$CLAUDE_TOOLS"
    [ "$DYNAMIC" -eq 1 ] && tools="Bash(sh:*), $tools"
    printf -- '---\n'
    printf 'description: %s\n' "$DESC"
    [ -n "$HINT" ]  && printf 'argument-hint: "%s"\n' "$HINT"
    [ -n "$tools" ] && printf 'allowed-tools: %s\n' "$tools"
    printf -- '---\n'
    if [ "$DYNAMIC" -eq 1 ]; then printf '%s\n\n' "$DYN_RESOLVER"; fi
    printf '%s\n' "$RENDERED_BODY"
    ;;
  opencode|antigravity)
    # opencode commands and Antigravity workflows: description frontmatter + body
    printf -- '---\ndescription: %s\n---\n' "$DESC"
    printf '%s\n' "$RENDERED_BODY"
    ;;
  codex)
    printf -- '---\n'
    printf 'description: %s\n' "$DESC"
    [ -n "$HINT" ] && printf 'argument-hint: %s\n' "$HINT"
    printf -- '---\n'
    printf '%s\n' "$RENDERED_BODY"
    ;;
  gemini)
    TQ="'''"   # TOML literal multiline-string delimiter (no escaping inside)
    printf '# generated by llm-wiki-kit from commands-src/%s.md — do not edit here\n' "$NAME"
    printf 'description = "%s"\n' "$DESC"
    printf 'prompt = %s\n' "$TQ"
    printf '%s\n' "$RENDERED_BODY"
    printf '%s\n' "$TQ"
    ;;
  cursor)
    printf '%s\n' "$RENDERED_BODY"
    ;;
esac
